version: '3.8'
services:
  svelte-frontend-tma:
    build: .
    container_name: roomio-tma
    ports:
      # Port 8081 đang dùng cho portal chủ trọ, anh đổi TMA sang 8082
      - "8082:80" 
    environment:
      # Sử dụng IP Gateway nội bộ của Docker để gọi thẳng qua Backend (tránh bị Firewall của VPS chặn)
      - API_TARGET=http://172.17.0.1:3000
    restart: always