version: '3.8'
services:
  svelte-frontend-tma:
    build: .
    container_name: roomio-tma
    ports:
      # Port 8081 đang dùng cho portal chủ trọ, anh đổi TMA sang 8082
      - "8082:80" 
    environment:
      # Sử dụng IP Public của VPS thay vì IP Tailscale cũ
      - API_TARGET=http://140.245.59.215:3000
    restart: always