version: '3.8'
services:
  svelte-frontend-tma:
    build: .
    container_name: roomio-tma
    ports:
      # Port 8081 đang dùng cho portal chủ trọ, anh đổi TMA sang 8082
      - "8082:80" 
    environment:
      - API_TARGET=http://100.102.69.100:3000
    restart: always